version: '3.8'

services:
  db:
    image: postgres:15
    container_name: defect_detection_db
    environment:
      POSTGRES_DB: defect_detection
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: 